# Generated by Django 4.2.6 on 2023-11-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomapp', '0003_doctoravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='monday_afternoon',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
    ]
