# Generated by Django 4.2.6 on 2023-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomapp', '0005_doctoravailability_patient_patient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='patient',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='monday_afternoon',
            field=models.BooleanField(default=False),
        ),
    ]
