# Generated by Django 4.2.6 on 2023-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomapp', '0006_remove_doctoravailability_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='doctor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='specialty',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
