# Generated by Django 4.2.6 on 2023-11-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomapp', '0007_doctoravailability_clinic_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='clinic_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor_photo',
            field=models.ImageField(upload_to='doctor_photos/'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='specialty',
            field=models.CharField(max_length=255),
        ),
    ]
